jwt:
  secret: "YourSuperSecretKeyThatShouldBeAtLeast32Characters!"
  issuer: "WatchParty"
  audience: "WatchParty"
  expirationDays: 7

mongodb:
  connectionString: "mongodb://localhost:27017"
  databaseName: "watchparty"

redis:
  connectionString: "localhost:6379"

app:
  apiUrl: "http://localhost:5000"
  frontendUrl: "http://localhost:3000"
